#!/bin/bash -e
if [[ ! -f "/home/spark-bb5949e1-667e-454e-8a6d-2d/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-bb5949e1-667e-454e-8a6d-2d/tmp/uv/uv_0.6.10_linux_amd64" "$@"
