#!/bin/bash -e
if [[ ! -f "/home/spark-caf31a87-41af-4900-92ea-c6/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-caf31a87-41af-4900-92ea-c6/tmp/uv/uv_0.6.10_linux_amd64" "$@"
